version: '3'

services:
  pipego-runner:
    image: ghcr.io/pipego/runner:latest
    network_mode: "host"
  pipego-scheduler:
    image: ghcr.io/pipego/scheduler:latest
    network_mode: "host"
    depends_on:
      - pipego-runner
